/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by Puck. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a Puck page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache as the page is written in /api/puck/route.ts
 */

import { Client } from "./client";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { getPage } from "../../lib/get-page";
import type { Data } from "@puckeditor/core";

const HEADER_PATH = "/_layout/header";
const FOOTER_PATH = "/_layout/footer";

const mergeLayout = (
  page: Data,
  header?: Data | null,
  footer?: Data | null
): Data => {
  const headerContent = header?.content ?? [];
  const footerContent = footer?.content ?? [];
  const pageContent = page?.content ?? [];

  return {
    ...page,
    content: [...headerContent, ...pageContent, ...footerContent],
  };
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}): Promise<Metadata> {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;

  return {
    title: getPage(path)?.root.props?.title,
  };
}

export default async function Page({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}) {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const data = getPage(path);

  if (!data) {
    return notFound();
  }

  if (path === HEADER_PATH || path === FOOTER_PATH) {
    return <Client data={data} />;
  }

  const header = getPage(HEADER_PATH);
  const footer = getPage(FOOTER_PATH);
  const merged = mergeLayout(data, header, footer);

  return <Client data={merged} />;
}

// Force Next.js to produce static pages: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
// Delete this if you need dynamic rendering, such as access to headers or cookies
export const dynamic = "force-static";
